# Generated by Django 5.0 on 2023-12-27 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_alter_cliente_nit_alter_factura_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
